### ISSUE TITLE
Docs should recommend esm.sh for Deno

### ISSUE THREAD

**Issue by gigawhip** [minimusubi/curseforge-api#1]
Thank you for making this, it's been a big help tonight.

I learned the hard way trying to use this in Deno that your two examples, which use `jsdelivr` and `unpkg`, will not provide TypeScript information to Deno, which will then throw a compiler error if you import an Enum such as `CurseForgeGameEnum`. In the past it was possible to use `skypack.dev` but this seems to no longer be stable. I eventually found that [the official Deno docs](https://deno.land/manual@v1.14.2/npm_nodejs/cdns#deno-friendly-cdns) recommend [`esm.sh`](esm.sh) which was apparently built specifically for Deno, and it worked like a charm! Example with full URL:

```ts
import {
  CurseForgeClient,
  CurseForgeGameEnum,
} from "https://esm.sh/curseforge-api@1.0.2";
```

**Comment by minimusubi** [comment]
Thank you for finding this!
